### PR TITLE
Update to Tokio 1.0

### PR DESCRIPTION
**Pull request by pimeys**
Closes: https://github.com/pimeys/a2/issues/51

@moh-abk could you validate this code works?

### CODE REVIEW

**Comment by moh-abk** [comment]
Sure, I'll do some testing and get back to you @pimeys

**Comment by dbrgn** [comment]
Testing this as well. I'll be able to give you feedback from production next week. (Remind me in case I forget!)

**Comment by pimeys** [comment]
Cool. I'll merge when people give green light that it works.

**Comment by threema-danilo** [comment]
So far, around 13k pushes went through this branch, and so far everything looks fine! 🙂

@pimeys would be great if you could tag a release!

**Comment by dbrgn** [comment]
So far, 13k pushes went through without any issues 🙂 Thanks for the update @pimeys, perfect timing.

Would be great if you could create a new release!

**Comment by pimeys** [comment]
https://crates.io/crates/a2/0.6.0 done

**Comment by dbrgn** [comment]
Awesome, thank you!

**Pull request merged**
